<?php 
/* 
 * Generated configuration file 
 * Generated by: phpMyAdmin 4.4.7 setup script 
 * Date: Mon, 25 May 2015 20:18:05 +0800 
 */ 

/* Servers configuration */ 
$i = 0; 

/* Server: MariaDB at 127.0.0.1 port 3306 [1] */ 
$i++; 
$cfg['Servers'][$i]['verbose'] = 'MariaDB at 127.0.0.1'; 
$cfg['Servers'][$i]['host'] = 'localhost'; 
$cfg['Servers'][$i]['port'] = 3306; 
$cfg['Servers'][$i]['socket'] = '/run/mysqld/mysqld.sock'; 
$cfg['Servers'][$i]['connect_type'] = 'tcp'; 
$cfg['Servers'][$i]['auth_type'] = 'cookie'; 
$cfg['Servers'][$i]['user'] = ''; 
$cfg['Servers'][$i]['password'] = ''; 
$cfg['Servers'][$i]['AllowRoot'] = false; 
$cfg['Servers'][$i]['hide_db'] = 'information_schema'; 

/* End of servers configuration */ 

$cfg['blowfish_secret'] = '55631107d0e7d3.25723883'; 
$cfg['DefaultLang'] = 'en'; 
$cfg['ServerDefault'] = 1; 
$cfg['UploadDir'] = ''; 
$cfg['SaveDir'] = ''; 

//this is for phpmyadmin configuration storage 
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin'; 
$cfg['Servers'][$i]['controluser'] = 'pma'; 
$cfg['Servers'][$i]['controlpass'] = 'pmapassword'; 
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark'; 
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns'; 
$cfg['Servers'][$i]['column_info'] = 'pma__column_info'; 
$cfg['Servers'][$i]['favorite'] = 'pma__favorite'; 
$cfg['Servers'][$i]['history'] = 'pma__history'; 
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding'; 
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages'; 
$cfg['Servers'][$i]['recent'] = 'pma__recent'; 
$cfg['Servers'][$i]['relation'] = 'pma__relation'; 
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches'; 
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords'; 
$cfg['Servers'][$i]['table_info'] = 'pma__table_info'; 
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs'; 
$cfg['Servers'][$i]['tracking'] = 'pma__tracking'; 
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig'; 
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups'; 
$cfg['Servers'][$i]['users'] = 'pma__users'; 
?>